/**
 * A curated subset of the Garmin FIT profile.
 *
 * The FIT profile is huge and grows with every SDK release, so this table is
 * deliberately *not* treated as exhaustive: the decoder falls back to
 * `mesg_<num>` / `field_<num>` for anything missing, keeps the raw values, and
 * reports them as unknown fields so they still show up in the Data Explorer.
 * Adding a row here upgrades a raw field to a named one — nothing else changes.
 */

export interface FitFieldDef {
  name: string;
  /** value = raw / scale - offset */
  scale?: number;
  offset?: number;
  units?: string;
  /** Name of an enum in `FIT_ENUMS`. */
  enum?: string;
  /** sint32 semicircles → degrees. */
  semicircles?: boolean;
  /** uint32 FIT seconds → epoch ms. */
  dateTime?: boolean;
}

export interface FitMesgDef {
  name: string;
  fields: Record<number, FitFieldDef>;
}

const f = (
  name: string,
  extra: Omit<FitFieldDef, 'name'> = {},
): FitFieldDef => ({ name, ...extra });

const ts = f('timestamp', { dateTime: true });

/* ------------------------------------------------------------------- enums */

export const FIT_ENUMS: Record<string, Record<number, string>> = {
  file: {
    1: 'device',
    2: 'settings',
    3: 'sport',
    4: 'activity',
    5: 'workout',
    6: 'course',
    7: 'schedules',
    9: 'weight',
    10: 'totals',
    11: 'goals',
    14: 'blood_pressure',
    15: 'monitoring_a',
    20: 'activity_summary',
    28: 'monitoring_daily',
    32: 'monitoring_b',
    34: 'segment',
    35: 'segment_list',
    40: 'exd_configuration',
  },
  gender: { 0: 'female', 1: 'male' },
  sport: {
    0: 'generic',
    1: 'running',
    2: 'cycling',
    3: 'transition',
    4: 'fitness_equipment',
    5: 'swimming',
    6: 'basketball',
    7: 'soccer',
    8: 'tennis',
    9: 'american_football',
    10: 'training',
    11: 'walking',
    12: 'cross_country_skiing',
    13: 'alpine_skiing',
    14: 'snowboarding',
    15: 'rowing',
    16: 'mountaineering',
    17: 'hiking',
    18: 'multisport',
    19: 'paddling',
    20: 'flying',
    21: 'e_biking',
    22: 'motorcycling',
    23: 'boating',
    24: 'driving',
    25: 'golf',
    26: 'hang_gliding',
    27: 'horseback_riding',
    28: 'hunting',
    29: 'fishing',
    30: 'inline_skating',
    31: 'rock_climbing',
    32: 'sailing',
    33: 'ice_skating',
    34: 'sky_diving',
    35: 'snowshoeing',
    36: 'snowmobiling',
    37: 'stand_up_paddleboarding',
    38: 'surfing',
    39: 'wakeboarding',
    40: 'water_skiing',
    41: 'kayaking',
    42: 'rafting',
    43: 'windsurfing',
    44: 'kitesurfing',
    45: 'tactical',
    46: 'jumpmaster',
    47: 'boxing',
    48: 'floor_climbing',
    49: 'baseball',
    53: 'diving',
    62: 'hiit',
    64: 'racket',
    65: 'wheelchair_push_walk',
    66: 'wheelchair_push_run',
    67: 'meditation',
    76: 'water_tubing',
    77: 'wakesurfing',
    254: 'all',
  },
  sub_sport: {
    0: 'generic',
    1: 'treadmill',
    2: 'street',
    3: 'trail',
    4: 'track',
    5: 'spin',
    6: 'indoor_cycling',
    7: 'road',
    8: 'mountain',
    9: 'downhill',
    10: 'recumbent',
    11: 'cyclocross',
    12: 'hand_cycling',
    13: 'track_cycling',
    14: 'indoor_rowing',
    15: 'elliptical',
    16: 'stair_climbing',
    17: 'lap_swimming',
    18: 'open_water',
    19: 'flexibility_training',
    20: 'strength_training',
    21: 'warm_up',
    22: 'match',
    23: 'exercise',
    24: 'challenge',
    25: 'indoor_skiing',
    26: 'cardio_training',
    27: 'indoor_walking',
    28: 'e_bike_fitness',
    29: 'bmx',
    30: 'casual_walking',
    31: 'speed_walking',
    32: 'bike_to_run_transition',
    33: 'run_to_bike_transition',
    34: 'swim_to_bike_transition',
    35: 'atv',
    36: 'motocross',
    37: 'backcountry',
    38: 'resort',
    39: 'rc_drone',
    40: 'wingsuit',
    41: 'whitewater',
    42: 'skate_skiing',
    43: 'yoga',
    44: 'pilates',
    45: 'indoor_running',
    46: 'gravel_cycling',
    47: 'e_bike_mountain',
    48: 'commuting',
    49: 'mixed_surface',
    50: 'navigate',
    51: 'track_me',
    52: 'map',
    53: 'single_gas_diving',
    58: 'virtual_activity',
    62: 'obstacle',
    65: 'breathing',
    88: 'ultra',
    89: 'indoor_climbing',
    90: 'bouldering',
  },
  event: {
    0: 'timer',
    3: 'workout',
    4: 'workout_step',
    5: 'power_down',
    6: 'power_up',
    7: 'off_course',
    8: 'session',
    9: 'lap',
    10: 'course_point',
    11: 'battery',
    12: 'virtual_partner_pace',
    13: 'hr_high_alert',
    14: 'hr_low_alert',
    15: 'speed_high_alert',
    16: 'speed_low_alert',
    17: 'cad_high_alert',
    18: 'cad_low_alert',
    19: 'power_high_alert',
    20: 'power_low_alert',
    21: 'recovery_hr',
    22: 'battery_low',
    23: 'time_duration_alert',
    24: 'distance_duration_alert',
    25: 'calorie_duration_alert',
    26: 'activity',
    27: 'fitness_equipment',
    28: 'length',
    32: 'user_marker',
    33: 'sport_point',
    36: 'calibration',
    42: 'front_gear_change',
    43: 'rear_gear_change',
    44: 'rider_position_change',
    45: 'elev_high_alert',
    46: 'elev_low_alert',
    47: 'comm_timeout',
    75: 'radar_threat_alert',
  },
  event_type: {
    0: 'start',
    1: 'stop',
    2: 'consecutive_depreciated',
    3: 'marker',
    4: 'stop_all',
    5: 'begin_depreciated',
    6: 'end_depreciated',
    7: 'end_all_depreciated',
    8: 'stop_disable',
    9: 'stop_disable_all',
  },
  lap_trigger: {
    0: 'manual',
    1: 'time',
    2: 'distance',
    3: 'position_start',
    4: 'position_lap',
    5: 'position_waypoint',
    6: 'position_marked',
    7: 'session_end',
    8: 'fitness_equipment',
  },
  session_trigger: { 0: 'activity_end', 1: 'manual', 2: 'auto_multi_sport', 3: 'fitness_equipment' },
  intensity: { 0: 'active', 1: 'rest', 2: 'warmup', 3: 'cooldown', 4: 'recovery', 5: 'interval', 6: 'other' },
  swim_stroke: {
    0: 'freestyle',
    1: 'backstroke',
    2: 'breaststroke',
    3: 'butterfly',
    4: 'drill',
    5: 'mixed',
    6: 'im',
  },
  activity_type: {
    0: 'generic',
    1: 'running',
    2: 'cycling',
    3: 'transition',
    4: 'fitness_equipment',
    5: 'swimming',
    6: 'walking',
    7: 'sedentary',
    8: 'stand',
    254: 'all',
  },
  sleep_level: {
    0: 'unmeasurable',
    1: 'awake',
    2: 'light',
    3: 'deep',
    4: 'rem',
  },
  hrv_status: { 0: 'none', 1: 'poor', 2: 'low', 3: 'unbalanced', 4: 'balanced' },
  activity_class: { 0: 'level', 100: 'athlete' },
  manufacturer: {
    1: 'garmin',
    2: 'garmin_fr405_antfs',
    3: 'zephyr',
    4: 'dayton',
    5: 'idt',
    6: 'srm',
    7: 'quarq',
    8: 'ibike',
    9: 'saris',
    13: 'dynastream',
    15: 'suunto',
    23: 'stages_cycling',
    32: 'wahoo_fitness',
    38: 'lezyne',
    41: 'favero_electronics',
    48: 'pioneer',
    58: 'sram',
    60: 'hammerhead',
    63: 'tacx',
    69: 'polar_electro',
    76: 'garmin_china',
    89: 'peloton',
    95: 'coros',
    260: 'zwift',
    263: 'wattbike',
    284: 'strava',
    294: 'concept2',
    301: 'form',
    305: 'hammerhead2',
  },
};

/* ---------------------------------------------------------------- messages */

export const FIT_MESSAGES: Record<number, FitMesgDef> = {
  0: {
    name: 'file_id',
    fields: {
      0: f('type', { enum: 'file' }),
      1: f('manufacturer', { enum: 'manufacturer' }),
      2: f('product'),
      3: f('serial_number'),
      4: f('time_created', { dateTime: true }),
      5: f('number'),
      8: f('product_name'),
    },
  },
  2: {
    name: 'device_settings',
    fields: {
      253: ts,
      1: f('utc_offset'),
      2: f('time_offset', { units: 's' }),
      5: f('time_zone_offset', { scale: 4, units: 'hr' }),
    },
  },
  3: {
    name: 'user_profile',
    fields: {
      253: ts,
      0: f('friendly_name'),
      1: f('gender', { enum: 'gender' }),
      2: f('age', { units: 'years' }),
      3: f('height', { scale: 100, units: 'm' }),
      4: f('weight', { scale: 10, units: 'kg' }),
      5: f('language'),
      6: f('elev_setting'),
      7: f('weight_setting'),
      8: f('resting_heart_rate', { units: 'bpm' }),
      9: f('default_max_running_heart_rate', { units: 'bpm' }),
      10: f('default_max_biking_heart_rate', { units: 'bpm' }),
      11: f('default_max_heart_rate', { units: 'bpm' }),
      12: f('hr_setting'),
      13: f('speed_setting'),
      14: f('dist_setting'),
      16: f('power_setting'),
      17: f('activity_class', { enum: 'activity_class' }),
      18: f('position_setting'),
      21: f('temperature_setting'),
      22: f('local_id'),
      31: f('global_id'),
    },
  },
  7: {
    name: 'zones_target',
    fields: {
      1: f('max_heart_rate', { units: 'bpm' }),
      2: f('threshold_heart_rate', { units: 'bpm' }),
      3: f('functional_threshold_power', { units: 'watts' }),
      5: f('hr_calc_type'),
      7: f('pwr_calc_type'),
    },
  },
  8: { name: 'hr_zone', fields: { 254: f('message_index'), 1: f('high_bpm', { units: 'bpm' }), 2: f('name') } },
  12: { name: 'sport', fields: { 0: f('sport', { enum: 'sport' }), 1: f('sub_sport', { enum: 'sub_sport' }), 3: f('name') } },
  18: {
    name: 'session',
    fields: {
      253: ts,
      254: f('message_index'),
      0: f('event', { enum: 'event' }),
      1: f('event_type', { enum: 'event_type' }),
      2: f('start_time', { dateTime: true }),
      3: f('start_position_lat', { semicircles: true, units: 'deg' }),
      4: f('start_position_long', { semicircles: true, units: 'deg' }),
      5: f('sport', { enum: 'sport' }),
      6: f('sub_sport', { enum: 'sub_sport' }),
      7: f('total_elapsed_time', { scale: 1000, units: 's' }),
      8: f('total_timer_time', { scale: 1000, units: 's' }),
      9: f('total_distance', { scale: 100, units: 'm' }),
      10: f('total_cycles', { units: 'cycles' }),
      11: f('total_calories', { units: 'kcal' }),
      13: f('total_fat_calories', { units: 'kcal' }),
      14: f('avg_speed', { scale: 1000, units: 'm/s' }),
      15: f('max_speed', { scale: 1000, units: 'm/s' }),
      16: f('avg_heart_rate', { units: 'bpm' }),
      17: f('max_heart_rate', { units: 'bpm' }),
      18: f('avg_cadence', { units: 'rpm' }),
      19: f('max_cadence', { units: 'rpm' }),
      20: f('avg_power', { units: 'watts' }),
      21: f('max_power', { units: 'watts' }),
      22: f('total_ascent', { units: 'm' }),
      23: f('total_descent', { units: 'm' }),
      24: f('total_training_effect', { scale: 10 }),
      25: f('first_lap_index'),
      26: f('num_laps'),
      27: f('event_group'),
      28: f('trigger', { enum: 'session_trigger' }),
      29: f('nec_lat', { semicircles: true, units: 'deg' }),
      30: f('nec_long', { semicircles: true, units: 'deg' }),
      31: f('swc_lat', { semicircles: true, units: 'deg' }),
      32: f('swc_long', { semicircles: true, units: 'deg' }),
      34: f('normalized_power', { units: 'watts' }),
      35: f('training_stress_score', { scale: 10, units: 'tss' }),
      36: f('intensity_factor', { scale: 1000 }),
      37: f('left_right_balance'),
      41: f('avg_stroke_count', { scale: 10, units: 'strokes/lap' }),
      42: f('avg_stroke_distance', { scale: 100, units: 'm' }),
      43: f('swim_stroke', { enum: 'swim_stroke' }),
      44: f('pool_length', { scale: 100, units: 'm' }),
      45: f('threshold_power', { units: 'watts' }),
      47: f('num_active_lengths'),
      48: f('total_work', { units: 'J' }),
      49: f('avg_altitude', { scale: 5, offset: 500, units: 'm' }),
      50: f('max_altitude', { scale: 5, offset: 500, units: 'm' }),
      51: f('gps_accuracy', { units: 'm' }),
      52: f('avg_grade', { scale: 100, units: '%' }),
      53: f('avg_pos_grade', { scale: 100, units: '%' }),
      54: f('avg_neg_grade', { scale: 100, units: '%' }),
      55: f('max_pos_grade', { scale: 100, units: '%' }),
      56: f('max_neg_grade', { scale: 100, units: '%' }),
      57: f('avg_temperature', { units: 'C' }),
      58: f('max_temperature', { units: 'C' }),
      59: f('total_moving_time', { scale: 1000, units: 's' }),
      60: f('avg_pos_vertical_speed', { scale: 1000, units: 'm/s' }),
      61: f('avg_neg_vertical_speed', { scale: 1000, units: 'm/s' }),
      62: f('max_pos_vertical_speed', { scale: 1000, units: 'm/s' }),
      63: f('max_neg_vertical_speed', { scale: 1000, units: 'm/s' }),
      64: f('min_heart_rate', { units: 'bpm' }),
      65: f('time_in_hr_zone', { scale: 1000, units: 's' }),
      66: f('time_in_speed_zone', { scale: 1000, units: 's' }),
      67: f('time_in_cadence_zone', { scale: 1000, units: 's' }),
      68: f('time_in_power_zone', { scale: 1000, units: 's' }),
      69: f('avg_lap_time', { scale: 1000, units: 's' }),
      70: f('best_lap_index'),
      71: f('min_altitude', { scale: 5, offset: 500, units: 'm' }),
      82: f('player_score'),
      83: f('opponent_score'),
      89: f('avg_vertical_oscillation', { scale: 10, units: 'mm' }),
      90: f('avg_stance_time_percent', { scale: 100, units: '%' }),
      91: f('avg_stance_time', { scale: 10, units: 'ms' }),
      92: f('avg_fractional_cadence', { scale: 128, units: 'rpm' }),
      93: f('max_fractional_cadence', { scale: 128, units: 'rpm' }),
      94: f('total_fractional_cycles', { scale: 128, units: 'cycles' }),
      101: f('avg_left_torque_effectiveness', { scale: 2, units: '%' }),
      102: f('avg_right_torque_effectiveness', { scale: 2, units: '%' }),
      103: f('avg_left_pedal_smoothness', { scale: 2, units: '%' }),
      104: f('avg_right_pedal_smoothness', { scale: 2, units: '%' }),
      105: f('avg_combined_pedal_smoothness', { scale: 2, units: '%' }),
      110: f('sport_profile_name'),
      111: f('sport_index'),
      112: f('time_standing', { scale: 1000, units: 's' }),
      113: f('stand_count'),
      124: f('enhanced_avg_speed', { scale: 1000, units: 'm/s' }),
      125: f('enhanced_max_speed', { scale: 1000, units: 'm/s' }),
      126: f('enhanced_avg_altitude', { scale: 5, offset: 500, units: 'm' }),
      127: f('enhanced_min_altitude', { scale: 5, offset: 500, units: 'm' }),
      128: f('enhanced_max_altitude', { scale: 5, offset: 500, units: 'm' }),
      137: f('total_anaerobic_training_effect', { scale: 10 }),
      139: f('avg_vam', { scale: 1000, units: 'm/s' }),
      168: f('total_grit'),
      169: f('total_flow'),
      181: f('avg_grit'),
      182: f('avg_flow'),
      194: f('total_fractional_ascent', { scale: 100, units: 'm' }),
      195: f('total_fractional_descent', { scale: 100, units: 'm' }),
      200: f('avg_core_temperature', { scale: 100, units: 'C' }),
      201: f('min_core_temperature', { scale: 100, units: 'C' }),
      202: f('max_core_temperature', { scale: 100, units: 'C' }),
    },
  },
  19: {
    name: 'lap',
    fields: {
      253: ts,
      254: f('message_index'),
      0: f('event', { enum: 'event' }),
      1: f('event_type', { enum: 'event_type' }),
      2: f('start_time', { dateTime: true }),
      3: f('start_position_lat', { semicircles: true, units: 'deg' }),
      4: f('start_position_long', { semicircles: true, units: 'deg' }),
      5: f('end_position_lat', { semicircles: true, units: 'deg' }),
      6: f('end_position_long', { semicircles: true, units: 'deg' }),
      7: f('total_elapsed_time', { scale: 1000, units: 's' }),
      8: f('total_timer_time', { scale: 1000, units: 's' }),
      9: f('total_distance', { scale: 100, units: 'm' }),
      10: f('total_cycles', { units: 'cycles' }),
      11: f('total_calories', { units: 'kcal' }),
      12: f('total_fat_calories', { units: 'kcal' }),
      13: f('avg_speed', { scale: 1000, units: 'm/s' }),
      14: f('max_speed', { scale: 1000, units: 'm/s' }),
      15: f('avg_heart_rate', { units: 'bpm' }),
      16: f('max_heart_rate', { units: 'bpm' }),
      17: f('avg_cadence', { units: 'rpm' }),
      18: f('max_cadence', { units: 'rpm' }),
      19: f('avg_power', { units: 'watts' }),
      20: f('max_power', { units: 'watts' }),
      21: f('total_ascent', { units: 'm' }),
      22: f('total_descent', { units: 'm' }),
      23: f('intensity', { enum: 'intensity' }),
      24: f('lap_trigger', { enum: 'lap_trigger' }),
      25: f('sport', { enum: 'sport' }),
      26: f('event_group'),
      32: f('num_lengths'),
      33: f('normalized_power', { units: 'watts' }),
      34: f('left_right_balance'),
      35: f('first_length_index'),
      37: f('avg_stroke_distance', { scale: 100, units: 'm' }),
      38: f('swim_stroke', { enum: 'swim_stroke' }),
      39: f('sub_sport', { enum: 'sub_sport' }),
      40: f('num_active_lengths'),
      41: f('total_work', { units: 'J' }),
      42: f('avg_altitude', { scale: 5, offset: 500, units: 'm' }),
      43: f('max_altitude', { scale: 5, offset: 500, units: 'm' }),
      44: f('gps_accuracy', { units: 'm' }),
      45: f('avg_grade', { scale: 100, units: '%' }),
      46: f('avg_pos_grade', { scale: 100, units: '%' }),
      47: f('avg_neg_grade', { scale: 100, units: '%' }),
      48: f('max_pos_grade', { scale: 100, units: '%' }),
      49: f('max_neg_grade', { scale: 100, units: '%' }),
      50: f('avg_temperature', { units: 'C' }),
      51: f('max_temperature', { units: 'C' }),
      52: f('total_moving_time', { scale: 1000, units: 's' }),
      57: f('time_in_hr_zone', { scale: 1000, units: 's' }),
      61: f('min_altitude', { scale: 5, offset: 500, units: 'm' }),
      62: f('min_heart_rate', { units: 'bpm' }),
      71: f('wkt_step_index'),
      77: f('avg_vertical_oscillation', { scale: 10, units: 'mm' }),
      78: f('avg_stance_time_percent', { scale: 100, units: '%' }),
      79: f('avg_stance_time', { scale: 10, units: 'ms' }),
      80: f('avg_fractional_cadence', { scale: 128, units: 'rpm' }),
      81: f('max_fractional_cadence', { scale: 128, units: 'rpm' }),
      110: f('enhanced_avg_speed', { scale: 1000, units: 'm/s' }),
      111: f('enhanced_max_speed', { scale: 1000, units: 'm/s' }),
      112: f('enhanced_avg_altitude', { scale: 5, offset: 500, units: 'm' }),
      113: f('enhanced_min_altitude', { scale: 5, offset: 500, units: 'm' }),
      114: f('enhanced_max_altitude', { scale: 5, offset: 500, units: 'm' }),
      121: f('avg_vam', { scale: 1000, units: 'm/s' }),
    },
  },
  20: {
    name: 'record',
    fields: {
      253: ts,
      0: f('position_lat', { semicircles: true, units: 'deg' }),
      1: f('position_long', { semicircles: true, units: 'deg' }),
      2: f('altitude', { scale: 5, offset: 500, units: 'm' }),
      3: f('heart_rate', { units: 'bpm' }),
      4: f('cadence', { units: 'rpm' }),
      5: f('distance', { scale: 100, units: 'm' }),
      6: f('speed', { scale: 1000, units: 'm/s' }),
      7: f('power', { units: 'watts' }),
      9: f('grade', { scale: 100, units: '%' }),
      10: f('resistance'),
      11: f('time_from_course', { scale: 1000, units: 's' }),
      12: f('cycle_length', { scale: 100, units: 'm' }),
      13: f('temperature', { units: 'C' }),
      17: f('cycles', { units: 'cycles' }),
      18: f('total_cycles', { units: 'cycles' }),
      20: f('accumulated_power', { units: 'watts' }),
      21: f('left_right_balance'),
      22: f('gps_accuracy', { units: 'm' }),
      23: f('vertical_speed', { scale: 1000, units: 'm/s' }),
      24: f('calories', { units: 'kcal' }),
      39: f('vertical_oscillation', { scale: 10, units: 'mm' }),
      40: f('stance_time_percent', { scale: 100, units: '%' }),
      41: f('stance_time', { scale: 10, units: 'ms' }),
      42: f('activity_type', { enum: 'activity_type' }),
      43: f('left_torque_effectiveness', { scale: 2, units: '%' }),
      44: f('right_torque_effectiveness', { scale: 2, units: '%' }),
      45: f('left_pedal_smoothness', { scale: 2, units: '%' }),
      46: f('right_pedal_smoothness', { scale: 2, units: '%' }),
      47: f('combined_pedal_smoothness', { scale: 2, units: '%' }),
      49: f('stroke_type'),
      50: f('zone'),
      51: f('ball_speed', { scale: 100, units: 'm/s' }),
      52: f('cadence256', { scale: 256, units: 'rpm' }),
      53: f('fractional_cadence', { scale: 128, units: 'rpm' }),
      54: f('total_hemoglobin_conc', { scale: 100, units: 'g/dL' }),
      57: f('saturated_hemoglobin_percent', { scale: 10, units: '%' }),
      61: f('device_index'),
      62: f('left_pco', { units: 'mm' }),
      63: f('right_pco', { units: 'mm' }),
      73: f('enhanced_speed', { scale: 1000, units: 'm/s' }),
      78: f('enhanced_altitude', { scale: 5, offset: 500, units: 'm' }),
      81: f('battery_soc', { scale: 2, units: '%' }),
      82: f('motor_power', { units: 'watts' }),
      83: f('vertical_ratio', { scale: 100, units: '%' }),
      84: f('stance_time_balance', { scale: 100, units: '%' }),
      85: f('step_length', { scale: 10, units: 'mm' }),
      108: f('enhanced_respiration_rate', { scale: 100, units: 'brpm' }),
      139: f('core_temperature', { scale: 100, units: 'C' }),
    },
  },
  21: {
    name: 'event',
    fields: {
      253: ts,
      0: f('event', { enum: 'event' }),
      1: f('event_type', { enum: 'event_type' }),
      2: f('data16'),
      3: f('data'),
      4: f('event_group'),
      7: f('score'),
      8: f('opponent_score'),
      15: f('radar_threat_level_max'),
    },
  },
  23: {
    name: 'device_info',
    fields: {
      253: ts,
      0: f('device_index'),
      1: f('device_type'),
      2: f('manufacturer', { enum: 'manufacturer' }),
      3: f('serial_number'),
      4: f('product'),
      5: f('software_version', { scale: 100 }),
      6: f('hardware_version'),
      7: f('cum_operating_time', { units: 's' }),
      10: f('battery_voltage', { scale: 256, units: 'V' }),
      11: f('battery_status'),
      20: f('ant_transmission_type'),
      21: f('ant_device_number'),
      22: f('ant_network'),
      25: f('source_type'),
      27: f('product_name'),
    },
  },
  30: {
    name: 'weight_scale',
    fields: {
      253: ts,
      0: f('weight', { scale: 100, units: 'kg' }),
      1: f('percent_fat', { scale: 100, units: '%' }),
      2: f('percent_hydration', { scale: 100, units: '%' }),
      3: f('visceral_fat_mass', { scale: 100, units: 'kg' }),
      4: f('bone_mass', { scale: 100, units: 'kg' }),
      5: f('muscle_mass', { scale: 100, units: 'kg' }),
      7: f('basal_met', { scale: 4, units: 'kcal/day' }),
      8: f('physique_rating'),
      9: f('active_met', { scale: 4, units: 'kcal/day' }),
      10: f('metabolic_age', { units: 'years' }),
      11: f('visceral_fat_rating'),
      12: f('user_profile_index'),
      13: f('bmi', { scale: 10, units: 'kg/m^2' }),
    },
  },
  34: {
    name: 'activity',
    fields: {
      253: ts,
      0: f('total_timer_time', { scale: 1000, units: 's' }),
      1: f('num_sessions'),
      2: f('type'),
      3: f('event', { enum: 'event' }),
      4: f('event_type', { enum: 'event_type' }),
      5: f('local_timestamp', { dateTime: true }),
      6: f('event_group'),
    },
  },
  49: { name: 'file_creator', fields: { 0: f('software_version'), 1: f('hardware_version') } },
  55: {
    name: 'monitoring',
    fields: {
      253: ts,
      0: f('device_index'),
      1: f('calories', { units: 'kcal' }),
      2: f('distance', { scale: 100, units: 'm' }),
      3: f('cycles', { scale: 2, units: 'cycles' }),
      4: f('active_time', { scale: 1000, units: 's' }),
      5: f('activity_type', { enum: 'activity_type' }),
      6: f('activity_subtype'),
      7: f('activity_level'),
      8: f('distance_16'),
      9: f('cycles_16'),
      10: f('active_time_16'),
      11: f('local_timestamp', { dateTime: true }),
      12: f('temperature', { scale: 100, units: 'C' }),
      14: f('temperature_min', { scale: 100, units: 'C' }),
      15: f('temperature_max', { scale: 100, units: 'C' }),
      16: f('activity_time', { units: 'minutes' }),
      19: f('active_calories', { units: 'kcal' }),
      24: f('current_activity_type_intensity'),
      25: f('timestamp_min_8'),
      26: f('timestamp_16'),
      27: f('heart_rate', { units: 'bpm' }),
      28: f('intensity', { scale: 10 }),
      29: f('duration_min', { units: 'min' }),
      30: f('duration', { units: 's' }),
      31: f('ascent', { scale: 1000, units: 'm' }),
      32: f('descent', { scale: 1000, units: 'm' }),
      33: f('moderate_activity_minutes', { units: 'minutes' }),
      34: f('vigorous_activity_minutes', { units: 'minutes' }),
    },
  },
  78: { name: 'hrv', fields: { 0: f('time', { scale: 1000, units: 's' }) } },
  103: {
    name: 'monitoring_info',
    fields: {
      253: ts,
      0: f('local_timestamp', { dateTime: true }),
      1: f('activity_type', { enum: 'activity_type' }),
      3: f('cycles_to_distance', { scale: 5000, units: 'm/cycle' }),
      4: f('cycles_to_calories', { scale: 5000, units: 'kcal/cycle' }),
      5: f('resting_metabolic_rate', { units: 'kcal/day' }),
    },
  },
  128: {
    name: 'weather_conditions',
    fields: { 253: ts, 0: f('weather_report'), 1: f('temperature', { units: 'C' }) },
  },
  132: {
    name: 'hr',
    fields: {
      253: ts,
      0: f('fractional_timestamp', { scale: 32768, units: 's' }),
      1: f('time256', { scale: 256, units: 's' }),
      6: f('filtered_bpm', { units: 'bpm' }),
      9: f('event_timestamp', { scale: 1024, units: 's' }),
      10: f('event_timestamp_12'),
    },
  },
  140: {
    name: 'respiration_rate',
    fields: { 253: ts, 0: f('respiration_rate', { scale: 100, units: 'brpm' }) },
  },
  142: {
    name: 'segment_lap',
    fields: {
      253: ts,
      254: f('message_index'),
      2: f('start_time', { dateTime: true }),
      7: f('total_elapsed_time', { scale: 1000, units: 's' }),
      8: f('total_timer_time', { scale: 1000, units: 's' }),
      9: f('total_distance', { scale: 100, units: 'm' }),
      29: f('name'),
    },
  },
  206: {
    name: 'field_description',
    fields: {
      0: f('developer_data_index'),
      1: f('field_definition_number'),
      2: f('fit_base_type_id'),
      3: f('field_name'),
      4: f('array'),
      5: f('components'),
      6: f('scale'),
      7: f('offset'),
      8: f('units'),
      9: f('bits'),
      10: f('accumulate'),
      13: f('fit_base_unit_id'),
      14: f('native_mesg_num'),
      15: f('native_field_num'),
    },
  },
  207: {
    name: 'developer_data_id',
    fields: {
      0: f('developer_id'),
      1: f('application_id'),
      2: f('manufacturer_id', { enum: 'manufacturer' }),
      3: f('developer_data_index'),
      4: f('application_version'),
    },
  },
  211: { name: 'spo2_data', fields: { 253: ts, 0: f('reading_spo2', { units: '%' }), 1: f('reading_confidence'), 2: f('mode') } },
  225: {
    name: 'set',
    fields: {
      254: f('timestamp', { dateTime: true }),
      0: f('duration', { scale: 1000, units: 's' }),
      3: f('repetitions'),
      4: f('weight', { scale: 16, units: 'kg' }),
      5: f('set_type'),
      6: f('start_time', { dateTime: true }),
      7: f('category'),
      9: f('exercise_name'),
    },
  },
  227: {
    name: 'stress_level',
    fields: { 0: f('stress_level_value'), 1: f('stress_level_time', { dateTime: true }) },
  },
  229: {
    name: 'max_met_data',
    fields: {
      0: f('update_time', { dateTime: true }),
      2: f('vo2_max', { scale: 10, units: 'mL/kg/min' }),
      5: f('sport', { enum: 'sport' }),
      6: f('sub_sport', { enum: 'sub_sport' }),
      8: f('max_met_category'),
      9: f('calibrated_data'),
      12: f('hr_source'),
      13: f('speed_source'),
    },
  },
  258: { name: 'dive_settings', fields: { 253: ts, 0: f('name') } },
  268: {
    name: 'dive_summary',
    fields: {
      253: ts,
      0: f('reference_mesg'),
      2: f('avg_depth', { scale: 1000, units: 'm' }),
      3: f('max_depth', { scale: 1000, units: 'm' }),
      9: f('bottom_time', { scale: 1000, units: 's' }),
    },
  },
  273: { name: 'ohr_settings', fields: { 253: ts, 0: f('enabled') } },
  346: { name: 'sleep_level', fields: { 253: ts, 0: f('sleep_level', { enum: 'sleep_level' }) } },
  370: {
    name: 'hrv_status_summary',
    fields: {
      253: ts,
      0: f('weekly_average', { scale: 128, units: 'ms' }),
      1: f('last_night_average', { scale: 128, units: 'ms' }),
      2: f('last_night_5_min_high', { scale: 128, units: 'ms' }),
      3: f('baseline_low_upper', { scale: 128, units: 'ms' }),
      4: f('baseline_balanced_lower', { scale: 128, units: 'ms' }),
      5: f('baseline_balanced_upper', { scale: 128, units: 'ms' }),
      6: f('status', { enum: 'hrv_status' }),
    },
  },
  371: { name: 'hrv_value', fields: { 253: ts, 0: f('value', { scale: 128, units: 'ms' }) } },
  375: {
    name: 'device_aux_pair',
    fields: { 253: ts },
  },
  398: {
    name: 'sleep_assessment',
    fields: {
      0: f('combined_awake_score'),
      1: f('awake_time_score'),
      2: f('awakenings_count_score'),
      3: f('deep_sleep_score'),
      4: f('sleep_duration_score'),
      5: f('light_sleep_score'),
      6: f('overall_sleep_score'),
      7: f('sleep_quality_score'),
      8: f('sleep_recovery_score'),
      9: f('rem_sleep_score'),
      10: f('sleep_restlessness_score'),
      11: f('awakenings_count'),
      14: f('interruptions_score'),
      15: f('average_stress_during_sleep', { scale: 100 }),
    },
  },
};

export function mesgName(num: number): string {
  return FIT_MESSAGES[num]?.name ?? `mesg_${num}`;
}

export function fieldDef(mesgNum: number, fieldNum: number): FitFieldDef | undefined {
  return FIT_MESSAGES[mesgNum]?.fields[fieldNum];
}

export function enumValue(enumName: string | undefined, raw: number): string | number {
  if (!enumName) return raw;
  const table = FIT_ENUMS[enumName];
  if (!table) return raw;
  return table[raw] ?? raw;
}
